### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by alex-taffe** [Alamofire/Alamofire#3461]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

Alamofire does not support Windows. This is related to #1935 as much of the work is the same

## Feature Request

Alamofire support on Windows

## Value to Alamofire

Alamofire should support all Swift supported platforms

## Work to be done

- [x] #3460 excludes NetworkReachabilityManager from Windows, as it is not available (issue #3459)
- [ ] The work from #3446 needs to be merged, as much of it applies to Windows as well
- [x] #3462 needs to be merged into Linux

**Comment by jshier** [comment]
This has been merged and will go out with the next release. Note that there will be no official support, as Foundation on Linux and Windows is buggy and incomplete. Thanks for your help!
